ALTER PROC [dbo].[IN_DIEM_MONHOC]
	@MALOP NCHAR(10) ,
	@MAMH NCHAR(10),
	@LAN SMALLINT
AS
SELECT DIEM.MASV,HO + ' ' + TEN AS HOTEN,DIEM
	FROM  DIEM JOIN SINHVIEN  ON DIEM.MASV = SINHVIEN  .MASV
				--JOIN LOP ON LOP .MALOP=SINHVIEN .MALOP 
				--JOIN MONHOC ON MONHOC .MAMH=DIEM .MAMH
		WHERE  MALOP =@MALOP AND LAN =@LAN AND MAMH = @MAMH 
		--IN_DIEM_MONHOC 'C13CQPM01','BAST01','1'