ALTER PROC [dbo].[IN_DSSV]
@MALOP NCHAR(10)
AS
BEGIN
	SELECT SINHVIEN.MASV,HO + ' ' + TEN AS HOTEN,PHAI,NGAYSINH,GHICHU
	FROM SINHVIEN 
	--FROM LOP JOIN SINHVIEN ON LOP .MALOP = SINHVIEN.MALOP
	WHERE MALOP =@MALOP 
END
--IN_DSSV 'C13CQKT01'